Commit prior to moving to /machine.

diff --git a/registry/Makefile.am b/registry/Makefile.am
--- a/registry/Makefile.am
+++ b/registry/Makefile.am
@@ -2,23 +2,37 @@
 #
 # Process this file with automake to produce Makefile.in
 
+#nobase_localstate_FILES	= \
+#    registry/__db.001 \
+#    registry/__db.002 \
+#    registry/__db.003 \
+#    registry/__db.004 \
+#    registry/registry.db
+LDMHOME			= @LDMHOME@
+REGISTRY_DIR		= $(DESTDIR)@REGISTRY_DIR@
 noinst_LTLIBRARIES      = lib.la
 EXTRA_DIST              = \
     backend-bdb.c \
     backend.hin \
+    backend.h \
     checkRegistry \
-    extractDecls \
     misc.hin \
+    misc.h \
     node.hin \
+    node.h \
     registry.hin \
+    registry.h \
     regutil.txt \
-    stringBuf.hin
+    stringBuf.hin \
+    stringBuf.h \
+    configDefaults.txt
 BUILT_SOURCES		= \
     backend.c backend.h \
     misc.h \
     node.h \
     registry.h \
-    stringBuf.h
+    stringBuf.h \
+    configDefaults.txt
 lib_la_SOURCES          = \
     backend.c \
     misc.c \
@@ -34,11 +48,12 @@ TAGS_FILES              = \
     $(top_srcdir)/Berkeley-DB/os/*.c \
     /usr/local/include/CUnit/CUnit.h \
     /usr/local/include/CUnit/Basic.h
-CPPFLAGS		= \
+AM_CPPFLAGS		= \
     -I$(top_srcdir) \
     -I$(top_srcdir)/ulog \
     -I$(top_srcdir)/protocol \
-    -I$(top_builddir)/Berkeley-DB/build_unix
+    -I$(top_builddir)/Berkeley-DB/build_unix \
+    -DREGISTRY_PATH='"$(REGISTRY_DIR)"'
 bin_PROGRAMS		= regutil
 LDADD			= \
     lib.la \
@@ -46,28 +61,72 @@ LDADD			= \
     $(top_builddir)/rpc/lib.la \
     $(top_builddir)/ulog/lib.la \
     $(top_builddir)/Berkeley-DB/build_unix/libdb-4.8.la
-CLEANFILES		= \
-    regutil.out \
-    backend.h \
-    misc.h \
-    node.h \
-    registry.h \
-    stringBuf.h
+dist_man1_MANS		= regutil.1
+CLEANFILES		= regutil.out backend.c
 
 backend.c:	backend-bdb.c
 	$(LN_S) backend-bdb.c $@
 
+registry.h:	registry.hin registry.c regpar.tab Makefile
+	awk '/@PARAMETER_NAME_DEFINITIONS@/{exit}{print}' \
+	    $(srcdir)/registry.hin >$@.tmp1
+	awk -F : '{printf "#define REG_%s \"%s\"\n", $$1, $$2}' \
+	    <$(srcdir)/regpar.tab >>$@.tmp1
+	awk '{if (doPrint)print}/@PARAMETER_NAME_DEFINITIONS@/{doPrint=1}' \
+	    $(srcdir)/registry.hin >>$@.tmp1
+	$(top_srcdir)/extractDecls $@.tmp1 $(srcdir)/registry.c >$@.tmp2
+	mv -f $@.tmp2 $@
+	rm -f $@.tmp1 $@.sed
+
 .hin.h:
-	$(srcdir)/extractDecls $(srcdir)/$*.hin $(srcdir)/$*.c >$@.tmp
+	$(top_srcdir)/extractDecls $(srcdir)/$*.hin $(srcdir)/$*.c >$@.tmp
 	mv -f $@.tmp $@
 backend.h:	backend.hin backend.c
 misc.h:		misc.hin misc.c
 node.h:		node.hin node.c
-registry.h:	registry.hin registry.c
 stringBuf.h:	stringBuf.hin stringBuf.c
 
 .c.i:
 	$(COMPILE) $(lib_la_CPPFLAGS) -E -o $@ $<
+
+#registry:
+#	mkdir $@
+#registry/registry.db:
+configDefaults.txt:	../config.h
+	(echo '#include <config.h>'; \
+	find $(top_srcdir) \( -path '*/registry' -o -path '*/Berkeley-DB' \) \
+	    -prune -o -name \*.c -print \
+	| xargs sed -n \
+	    '/reg_getString(/{N;s/\n//;s/.*reg[A-Za-z_]*(//;s/).*//;p}' \
+	| tr -s ', ' ' ' | awk '{print $$1, $$3}' ) >configDefaults.c
+	$(COMPILE) $(lib_la_CPPFLAGS) -E -o configDefaults.i configDefaults.c
+	rm configDefaults.c
+	sed -n '/^[^#]/s/"//gp' configDefaults.i >$@
+	rm configDefaults.i
+
+install-exec-local:	regpar.tab regutil
+	-mkdir -p $(REGISTRY_DIR)
+	./regutil -c
+	while IFS=: read name path desc default; do \
+	    ./regutil "$$path" >/dev/null 2>&1; \
+	    status=$$?; \
+	    if test $$status = 0; then \
+		echo "Already in registry: \"$$path\" "; \
+	    elif test $$status = 1; then \
+		if test "$$name" = HOSTNAME; then \
+		    ./regutil -s `uname -n` "$$path" || break; \
+		else \
+		    ./regutil -s "$$default" "$$path" || break; \
+		fi; \
+		echo "Added to registry: \"$$path\" "; \
+	    else \
+		echo 1>&2 "Error loading registry"; \
+		exit 1; \
+	    fi; \
+	done < regpar.tab
+
+uninstall-local:
+	rm -f $(DESTDIR)$(mandir)/man1/regutil.1
 
 if HAVE_CUNIT
 check_PROGRAMS		= testRegistry
@@ -87,6 +146,9 @@ TESTS			= checkRegistry
 
 debug:		testRegistry
 	$(TESTS_ENVIRONMENT) $(LIBTOOL) --mode=execute gdb testRegistry
+
+debug-regutil:		regutil
+	$(TESTS_ENVIRONMENT) $(LIBTOOL) --mode=execute gdb regutil
 
 valgrind:	testRegistry
 	$(TESTS_ENVIRONMENT) $(LIBTOOL) --mode=execute valgrind \
diff --git a/registry/Makefile.in b/registry/Makefile.in
--- a/registry/Makefile.in
+++ b/registry/Makefile.in
@@ -42,7 +42,8 @@ host_triplet = @host@
 bin_PROGRAMS = regutil$(EXEEXT)
 @HAVE_CUNIT_TRUE@check_PROGRAMS = testRegistry$(EXEEXT)
 subdir = registry
-DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
+DIST_COMMON = $(dist_man1_MANS) $(srcdir)/Makefile.am \
+	$(srcdir)/Makefile.in $(srcdir)/regpar.tab.in
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/acinclude.m4 \
 	$(top_srcdir)/configure.ac
@@ -50,14 +51,14 @@ am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
 	$(ACLOCAL_M4)
 mkinstalldirs = $(install_sh) -d
 CONFIG_HEADER = $(top_builddir)/config.h
-CONFIG_CLEAN_FILES =
+CONFIG_CLEAN_FILES = regpar.tab
 CONFIG_CLEAN_VPATH_FILES =
 LTLIBRARIES = $(noinst_LTLIBRARIES)
 lib_la_LIBADD =
 am_lib_la_OBJECTS = backend.lo misc.lo node.lo registry.lo \
 	stringBuf.lo
 lib_la_OBJECTS = $(am_lib_la_OBJECTS)
-am__installdirs = "$(DESTDIR)$(bindir)"
+am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"
 PROGRAMS = $(bin_PROGRAMS)
 regutil_SOURCES = regutil.c
 regutil_OBJECTS = regutil.$(OBJEXT)
@@ -87,6 +88,30 @@ LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
 	$(LDFLAGS) -o $@
 SOURCES = $(lib_la_SOURCES) regutil.c testRegistry.c
 DIST_SOURCES = $(lib_la_SOURCES) regutil.c testRegistry.c
+am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
+am__vpath_adj = case $$p in \
+    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
+    *) f=$$p;; \
+  esac;
+am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
+am__install_max = 40
+am__nobase_strip_setup = \
+  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
+am__nobase_strip = \
+  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
+am__nobase_list = $(am__nobase_strip_setup); \
+  for p in $$list; do echo "$$p $$p"; done | \
+  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
+  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
+    if (++n[$$2] == $(am__install_max)) \
+      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
+    END { for (dir in files) print dir, files[dir] }'
+am__base_list = \
+  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
+  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
+man1dir = $(mandir)/man1
+NROFF = nroff
+MANS = $(dist_man1_MANS)
 ETAGS = etags
 CTAGS = ctags
 am__tty_colors = \
@@ -104,12 +129,7 @@ CC = @CC@
 CCDEPMODE = @CCDEPMODE@
 CFLAGS = @CFLAGS@
 CPP = @CPP@
-CPPFLAGS = \
-    -I$(top_srcdir) \
-    -I$(top_srcdir)/ulog \
-    -I$(top_srcdir)/protocol \
-    -I$(top_builddir)/Berkeley-DB/build_unix
-
+CPPFLAGS = @CPPFLAGS@
 CPPFLAGS_CUNIT = @CPPFLAGS_CUNIT@
 CXX = @CXX@
 CXXCPP = @CXXCPP@
@@ -135,6 +155,13 @@ INSTALL_PROGRAM = @INSTALL_PROGRAM@
 INSTALL_SCRIPT = @INSTALL_SCRIPT@
 INSTALL_STRIP_PROGRAM = @INSTALL_STRIP_PROGRAM@
 LDFLAGS = @LDFLAGS@
+
+#nobase_localstate_FILES	= \
+#    registry/__db.001 \
+#    registry/__db.002 \
+#    registry/__db.003 \
+#    registry/__db.004 \
+#    registry/registry.db
 LDMHOME = @LDMHOME@
 LDM_LOGFILE = @LDM_LOGFILE@
 LDM_PORT = @LDM_PORT@
@@ -145,6 +172,7 @@ LIBS = @LIBS@
 LIBS_CUNIT = @LIBS_CUNIT@
 LIBTOOL = @LIBTOOL@
 LN_S = @LN_S@
+LOGS_DIR = @LOGS_DIR@
 LOG_LDM = @LOG_LDM@
 LTLIBOBJS = @LTLIBOBJS@
 MAKEINFO = @MAKEINFO@
@@ -165,7 +193,9 @@ PATH_SEPARATOR = @PATH_SEPARATOR@
 PERL = @PERL@
 PQ_PATH = @PQ_PATH@
 PQ_SUBDIR = @PQ_SUBDIR@
+QUEUE_DIR = @QUEUE_DIR@
 RANLIB = @RANLIB@
+REGISTRY_DIR = $(DESTDIR)@REGISTRY_DIR@
 RPCGEN = @RPCGEN@
 SED = @SED@
 SET_MAKE = @SET_MAKE@
@@ -237,20 +267,26 @@ noinst_LTLIBRARIES = lib.la
 EXTRA_DIST = \
     backend-bdb.c \
     backend.hin \
+    backend.h \
     checkRegistry \
-    extractDecls \
     misc.hin \
+    misc.h \
     node.hin \
+    node.h \
     registry.hin \
+    registry.h \
     regutil.txt \
-    stringBuf.hin
+    stringBuf.hin \
+    stringBuf.h \
+    configDefaults.txt
 
 BUILT_SOURCES = \
     backend.c backend.h \
     misc.h \
     node.h \
     registry.h \
-    stringBuf.h
+    stringBuf.h \
+    configDefaults.txt
 
 lib_la_SOURCES = \
     backend.c \
@@ -269,6 +305,13 @@ TAGS_FILES = \
     /usr/local/include/CUnit/CUnit.h \
     /usr/local/include/CUnit/Basic.h
 
+AM_CPPFLAGS = \
+    -I$(top_srcdir) \
+    -I$(top_srcdir)/ulog \
+    -I$(top_srcdir)/protocol \
+    -I$(top_builddir)/Berkeley-DB/build_unix \
+    -DREGISTRY_PATH='"$(REGISTRY_DIR)"'
+
 LDADD = \
     lib.la \
     $(top_builddir)/protocol/lib.la \
@@ -276,14 +319,8 @@ LDADD = \
     $(top_builddir)/ulog/lib.la \
     $(top_builddir)/Berkeley-DB/build_unix/libdb-4.8.la
 
-CLEANFILES = \
-    regutil.out \
-    backend.h \
-    misc.h \
-    node.h \
-    registry.h \
-    stringBuf.h
-
+dist_man1_MANS = regutil.1
+CLEANFILES = regutil.out backend.c
 @HAVE_CUNIT_TRUE@testRegistry_CPPFLAGS = \
 @HAVE_CUNIT_TRUE@    -I$(top_srcdir)/protocol \
 @HAVE_CUNIT_TRUE@    -I$(top_srcdir)/ulog \
@@ -334,6 +371,8 @@ $(top_srcdir)/configure:  $(am__configure_deps)
 $(ACLOCAL_M4):  $(am__aclocal_m4_deps)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
 $(am__aclocal_m4_deps):
+regpar.tab: $(top_builddir)/config.status $(srcdir)/regpar.tab.in
+	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
 
 clean-noinstLTLIBRARIES:
 	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)
@@ -461,6 +500,40 @@ mostlyclean-libtool:
 
 clean-libtool:
 	-rm -rf .libs _libs
+install-man1: $(dist_man1_MANS)
+	@$(NORMAL_INSTALL)
+	test -z "$(man1dir)" || $(MKDIR_P) "$(DESTDIR)$(man1dir)"
+	@list='$(dist_man1_MANS)'; test -n "$(man1dir)" || exit 0; \
+	{ for i in $$list; do echo "$$i"; done; \
+	} | while read p; do \
+	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
+	  echo "$$d$$p"; echo "$$p"; \
+	done | \
+	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
+	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
+	sed 'N;N;s,\n, ,g' | { \
+	list=; while read file base inst; do \
+	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
+	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
+	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
+	  fi; \
+	done; \
+	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
+	while read files; do \
+	  test -z "$$files" || { \
+	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
+	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
+	done; }
+
+uninstall-man1:
+	@$(NORMAL_UNINSTALL)
+	@list='$(dist_man1_MANS)'; test -n "$(man1dir)" || exit 0; \
+	files=`{ for i in $$list; do echo "$$i"; done; \
+	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
+	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
+	test -z "$$files" || { \
+	  echo " ( cd '$(DESTDIR)$(man1dir)' && rm -f" $$files ")"; \
+	  cd "$(DESTDIR)$(man1dir)" && rm -f $$files; }
 
 ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
 	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
@@ -607,6 +680,19 @@ check-TESTS: $(TESTS)
 	else :; fi
 
 distdir: $(DISTFILES)
+	@list='$(MANS)'; if test -n "$$list"; then \
+	  list=`for p in $$list; do \
+	    if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
+	    if test -f "$$d$$p"; then echo "$$d$$p"; else :; fi; done`; \
+	  if test -n "$$list" && \
+	    grep 'ab help2man is required to generate this page' $$list >/dev/null; then \
+	    echo "error: found man pages containing the \`missing help2man' replacement text:" >&2; \
+	    grep -l 'ab help2man is required to generate this page' $$list | sed 's/^/         /' >&2; \
+	    echo "       to fix them, install help2man, remove and regenerate the man pages;" >&2; \
+	    echo "       typically \`make maintainer-clean' will remove them" >&2; \
+	    exit 1; \
+	  else :; fi; \
+	else :; fi
 	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
 	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
 	list='$(DISTFILES)'; \
@@ -641,9 +727,9 @@ check-am: all-am
 	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: $(BUILT_SOURCES)
 	$(MAKE) $(AM_MAKEFLAGS) check-am
-all-am: Makefile $(LTLIBRARIES) $(PROGRAMS)
+all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(MANS)
 installdirs:
-	for dir in "$(DESTDIR)$(bindir)"; do \
+	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"; do \
 	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
 	done
 install: $(BUILT_SOURCES)
@@ -697,13 +783,13 @@ info: info-am
 
 info-am:
 
-install-data-am:
+install-data-am: install-man
 
 install-dvi: install-dvi-am
 
 install-dvi-am:
 
-install-exec-am: install-binPROGRAMS
+install-exec-am: install-binPROGRAMS install-exec-local
 
 install-html: install-html-am
 
@@ -713,7 +799,7 @@ install-info: install-info-am
 
 install-info-am:
 
-install-man:
+install-man: install-man1
 
 install-pdf: install-pdf-am
 
@@ -743,7 +829,9 @@ ps: ps-am
 
 ps-am:
 
-uninstall-am: uninstall-binPROGRAMS
+uninstall-am: uninstall-binPROGRAMS uninstall-local uninstall-man
+
+uninstall-man: uninstall-man1
 
 .MAKE: all check check-am install install-am install-strip
 
@@ -754,32 +842,86 @@ uninstall-am: uninstall-binPROGRAMS
 	distclean-tags distdir dvi dvi-am html html-am info info-am \
 	install install-am install-binPROGRAMS install-data \
 	install-data-am install-dvi install-dvi-am install-exec \
-	install-exec-am install-html install-html-am install-info \
-	install-info-am install-man install-pdf install-pdf-am \
-	install-ps install-ps-am install-strip installcheck \
-	installcheck-am installdirs maintainer-clean \
-	maintainer-clean-generic mostlyclean mostlyclean-compile \
-	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
-	tags uninstall uninstall-am uninstall-binPROGRAMS
+	install-exec-am install-exec-local install-html \
+	install-html-am install-info install-info-am install-man \
+	install-man1 install-pdf install-pdf-am install-ps \
+	install-ps-am install-strip installcheck installcheck-am \
+	installdirs maintainer-clean maintainer-clean-generic \
+	mostlyclean mostlyclean-compile mostlyclean-generic \
+	mostlyclean-libtool pdf pdf-am ps ps-am tags uninstall \
+	uninstall-am uninstall-binPROGRAMS uninstall-local \
+	uninstall-man uninstall-man1
 
 
 backend.c:	backend-bdb.c
 	$(LN_S) backend-bdb.c $@
 
+registry.h:	registry.hin registry.c regpar.tab Makefile
+	awk '/@PARAMETER_NAME_DEFINITIONS@/{exit}{print}' \
+	    $(srcdir)/registry.hin >$@.tmp1
+	awk -F : '{printf "#define REG_%s \"%s\"\n", $$1, $$2}' \
+	    <$(srcdir)/regpar.tab >>$@.tmp1
+	awk '{if (doPrint)print}/@PARAMETER_NAME_DEFINITIONS@/{doPrint=1}' \
+	    $(srcdir)/registry.hin >>$@.tmp1
+	$(top_srcdir)/extractDecls $@.tmp1 $(srcdir)/registry.c >$@.tmp2
+	mv -f $@.tmp2 $@
+	rm -f $@.tmp1 $@.sed
+
 .hin.h:
-	$(srcdir)/extractDecls $(srcdir)/$*.hin $(srcdir)/$*.c >$@.tmp
+	$(top_srcdir)/extractDecls $(srcdir)/$*.hin $(srcdir)/$*.c >$@.tmp
 	mv -f $@.tmp $@
 backend.h:	backend.hin backend.c
 misc.h:		misc.hin misc.c
 node.h:		node.hin node.c
-registry.h:	registry.hin registry.c
 stringBuf.h:	stringBuf.hin stringBuf.c
 
 .c.i:
 	$(COMPILE) $(lib_la_CPPFLAGS) -E -o $@ $<
 
+#registry:
+#	mkdir $@
+#registry/registry.db:
+configDefaults.txt:	../config.h
+	(echo '#include <config.h>'; \
+	find $(top_srcdir) \( -path '*/registry' -o -path '*/Berkeley-DB' \) \
+	    -prune -o -name \*.c -print \
+	| xargs sed -n \
+	    '/reg_getString(/{N;s/\n//;s/.*reg[A-Za-z_]*(//;s/).*//;p}' \
+	| tr -s ', ' ' ' | awk '{print $$1, $$3}' ) >configDefaults.c
+	$(COMPILE) $(lib_la_CPPFLAGS) -E -o configDefaults.i configDefaults.c
+	rm configDefaults.c
+	sed -n '/^[^#]/s/"//gp' configDefaults.i >$@
+	rm configDefaults.i
+
+install-exec-local:	regpar.tab regutil
+	-mkdir -p $(REGISTRY_DIR)
+	./regutil -c
+	while IFS=: read name path desc default; do \
+	    ./regutil "$$path" >/dev/null 2>&1; \
+	    status=$$?; \
+	    if test $$status = 0; then \
+		echo "Already in registry: \"$$path\" "; \
+	    elif test $$status = 1; then \
+		if test "$$name" = HOSTNAME; then \
+		    ./regutil -s `uname -n` "$$path" || break; \
+		else \
+		    ./regutil -s "$$default" "$$path" || break; \
+		fi; \
+		echo "Added to registry: \"$$path\" "; \
+	    else \
+		echo 1>&2 "Error loading registry"; \
+		exit 1; \
+	    fi; \
+	done < regpar.tab
+
+uninstall-local:
+	rm -f $(DESTDIR)$(mandir)/man1/regutil.1
+
 @HAVE_CUNIT_TRUE@debug:		testRegistry
 @HAVE_CUNIT_TRUE@	$(TESTS_ENVIRONMENT) $(LIBTOOL) --mode=execute gdb testRegistry
+
+@HAVE_CUNIT_TRUE@debug-regutil:		regutil
+@HAVE_CUNIT_TRUE@	$(TESTS_ENVIRONMENT) $(LIBTOOL) --mode=execute gdb regutil
 
 @HAVE_CUNIT_TRUE@valgrind:	testRegistry
 @HAVE_CUNIT_TRUE@	$(TESTS_ENVIRONMENT) $(LIBTOOL) --mode=execute valgrind \
