Make more robust. Add error messages.

diff --git a/mcast_lib/ldm7/vlanUtil b/mcast_lib/ldm7/vlanUtil
--- a/mcast_lib/ldm7/vlanUtil
+++ b/mcast_lib/ldm7/vlanUtil
@@ -21,56 +21,99 @@ EOF
 }
 
 # Destroys an existing VLAN if it exists
-destroy() {
+destroy()
+{
     virtIface="${1:?Virtual interface not specified}"
     srvrAddr="${2}"
+    status=0
 
-    # Delete route if receiver and route exists
+    # Remove route if receiver and route exists
     if test "$srvrAddr"; then
         if ip route show "$srvrAddr" | fgrep "$virtIface" >/dev/null 2>&1; then
-            ip route del "$srvrAddr/32" dev "$virtIface"
+            if ! ip route del "$srvrAddr/32" dev "$virtIface"; then
+                echo 1>&2 "Couldn't remove interface $virtIface as route to $srvrAddr"
+                status=1;
+            fi
         fi
     fi
 
-    # Delete address of virtual interface if it exists
+    # Remove address of virtual interface if it exists
     ifaceAddr=$(ip addr show dev "$virtIface" 2>/dev/null | 
             awk '/ *inet / {print $2;}' | sed 's;/.*;;')
     if test "$ifaceAddr"; then
-        ip addr del "$ifaceAddr/32" dev "$virtIface"
+        if ! ip addr del "$ifaceAddr/32" dev "$virtIface"; then
+            echo 1>&2 "Couldn't remove address $ifaceAddr from interface $virtIface"
+            status=1
+        fi
     fi
 
     # Delete virtual interface if it exists
     if ip link show dev "$virtIface" >/dev/null 2>&1; then
-        ip link set dev "$virtIface" down
-        ip link del dev "$virtIface"
+        if ! ip link set dev "$virtIface" down; then
+            echo 1>&2 "Couldn't disable interface $virtIface"
+            status=1
+        else
+            if ! ip link del dev "$virtIface"; then
+                echo 1>&2 "Couldn't delete interface $virtIface"
+                status=1
+            fi
+        fi
     fi
+    
+    return $status
 }
 
 # Creates a VLAN. Destroys any previously-existing one.
-create() {
+create()
+{
     virtIface="${1:?Virtual interface not specified}"
     ifaceAddr="${2:?Virtual interface\'s address not specified}"
     srvrAddr="${3}"
+    status=0
 
     # If this is receiver, then ensure that VLAN doesn't exist
     if test "$srvrAddr"; then
-        (destroy "$virtIface" "$srvrAddr") # In subshell so parameters not overwritten
+        # In subshell so parameters not overwritten
+        if ! (destroy "$virtIface" "$srvrAddr"); then
+            echo 1>&2 "Couldn't destroy previous VLAN"
+            status=1
+        fi
     fi
 
-    # Obtain name of physical interface and VLAN ID
-    set `echo $virtIface | tr . ' '`
-    phyIface="${1:?Physical interface not specified}"
-    vlanId="${2:?VLAN ID not specified}"
+    if test $status -eq 0; then
+        # Obtain name of physical interface and VLAN ID
+        set `echo $virtIface | tr . ' '`
+        phyIface="${1:?Physical interface not specified}"
+        vlanId="${2:?VLAN ID not specified}"
 
-    # Create VLAN
-    ip link add link "$phyIface" name "$virtIface" type vlan id "$vlanId"
-    ip link set dev "$virtIface" up            # Must be before route is added
-    ip addr add "$ifaceAddr/32" dev "$virtIface"    
+        # Create VLAN
+        if ! ip link add link "$phyIface" name "$virtIface" type vlan id "$vlanId"; then
+            echo 1>&2 "Couldn't create VLAN interface $virtIface"
+            status=1
+        else
+            # Must be before route is added
+            if ! ip link set dev "$virtIface" up; then
+                echo 1>&2 "Couldn't enable interface $virtIface"
+                status=1
+            else
+                if ! ip addr add "$ifaceAddr/32" dev "$virtIface"; then
+                    echo 1>&2 "Couldn't add address $ifaceAddr to interface $virtIface"
+                    status=1
+                fi
+            fi
+        fi
 
-    # If this is receiver, then add route to sending FMTP server
-    if test "$srvrAddr"; then
-        ip route add "$srvrAddr/32" dev "$virtIface" # Must be after interface is up
+        # If this is receiver, then add route to sending FMTP server
+        if test $status -eq 0 -a "$srvrAddr"; then
+            # Must be after interface is up
+            if ! ip route add "$srvrAddr/32" dev "$virtIface"; then
+                echo 1>&2 "Couldn't add interface $virtIface as route to $srvrAddr"
+                status=1
+            fi
+        fi
     fi
+    
+    return $status
 }
 
 action="${1:?Action not specified}"
